data:
  augmentation:
    brightness_range: 0.2
    enabled: true
    noise_std: 0.01
    rotation_range: 15
    scale_range:
    - 0.9
    - 1.1
  data_root: /path/to/FungiTastic
  data_subset: Mini
  image_size: 300
  sample_ratio: null
  train_split: train
  val_split: val
debug:
  enabled: false
  max_samples: 100
  profile: false
  verbose: true
evaluation:
  metrics:
  - iou
  - l1
  - offset_magnitude
  save_predictions: true
  val_freq: 1
  visualize_samples: 10
hqsam:
  checkpoint: /path/to/hqsam_weights.pth
  checkpoint_path: /path/to/hqsam_weights.pth
  device: cuda
  model_type: vit_h
loss:
  iou_weight: 2.0
  l1_weight: 1.0
  total_variation_weight: 0.1
model:
  hidden_dim: 256
  max_offset: 50
  num_heads: 8
optimization:
  feature_cache:
    auto_detect: true
    cache_dir: ./features
    enabled: true
  performance:
    batch_size_multiplier: 1.0
    data_sampling: null
    use_amp: false
output:
  checkpoint_dir: ./checkpoints/box_refinement
  log_dir: ./logs/box_refinement
  log_freq: 10
  save_dir: ./outputs/box_refinement
  save_freq: 5
  vis_freq: 100
  visualization_dir: ./visualizations/box_refinement
refinement:
  max_iter: 3
  stop_threshold: 1.0
training:
  batch_size: 16
  epochs: 30
  feature_cache: true
  learning_rate: 1e-4
  lr_scheduler: cosine
  use_amp: false
  warmup_epochs: 5
  weight_decay: 1e-5
